name: Build Docker image

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  build-image:
    name: Build Docker Image
    uses: cupcakearmy/workflows/.github/workflows/docker-build.yml@main
    with:
      image: cupcakearmy/glyphance
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
